### ISSUE TITLE
Documentation is incorrect on ability to import non-internal themes

### ISSUE THREAD

**Issue by stefanoborini** [rstudio/shinythemes#16]
Documentation states:

```
How to use other Bootstrap themes
If you want to use a Bootstrap theme that isn’t included in shinythemes, you can include it in an app’s www/ subdirectory. The directory structure would be like this:

myapp
 |-- server.R
 |-- ui.R
 |-- www/
      |-- mytheme.css
Files in the www/ directory are automatically made available to your app. Your ui.R file would look like this:

fluidPage(
  theme = "mytheme.css",
  ...
)
```

This is not the case. Adding a file produces an error 
```
Error in shinythemes::shinytheme("mytheme.css") : 
  mytheme.css is not an available theme. Valid themes are: cerulean, cosmo, cyborg, darkly, flatly, journal, lumen, paper, readable, sandstone, simplex, slate, spacelab, superhero, united, yeti.
```
And there's nothing in the code that shows it can perform this operation.

**Comment by wch** [comment]
I'm not able to reproduce your problem. This app works fine in both Shiny 1.5.0 and Shiny 1.6.0:

```R
shinyApp(
  ui = fluidPage(
    theme = "test.css",
    div("hello")
  ),
  server = function(input, output) {}
)
```

There is a www/test.css file that looks like this:

```css
body {
  color: red;
}
```

Note that the [documentation](https://rstudio.github.io/shinythemes/#how-to-use-other-bootstrap-themes) that you're referring to does not involve the use of the shinythemes package. It says how to use other CSS files that are not included with shinythemes.
