### ISSUE TITLE
Should add live theme chooser component

### ISSUE THREAD

**Issue by wch** [rstudio/shinythemes#2]
For people who are developing an app, it would be nice to be able to select a theme on a live, running app. shinythemes could include a theme selector component (which would be a `selectInput`) and the corresponding server and JS code to replace the app's current bootstrap.css with whichever one is selected.

**Comment by daattali** [comment]
Hasn't this been implemented already? Which means this repo is at 0 issues!

**Comment by wch** [comment]
You're right!
