### ISSUE TITLE
update to bootswatch 4

### ISSUE THREAD

**Issue by maxheld83** [rstudio/shinythemes#4]
there's a newer set of themes here: https://bootswatch.com

Would be really cool if they could be supported out of the box.

Fantastic work, as always!

**Comment by wch** [comment]
Sorry, it's not possible to use Bootswatch 4, since it's built on Bootstrap 4, and Shiny is built on Bootstrap 3.

At some point in the future Shiny may migrate to Bootstrap 4, but until then, shinythemes needs to stay with Bootstrap 3. (https://bootswatch.com/3/)
